-- ==============================================================================
-- Fairwork Pulse: Production PostgreSQL Schema & Zero-Knowledge RLS Policies
-- ==============================================================================

-- 1. PROFILES
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  display_name text,
  phone text,
  preferred_sector text default 'construction',
  language_preference text default 'en',
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

alter table public.profiles enable row level security;

create policy "Users can view own profile"
  on public.profiles for select
  using ((select auth.uid()) = id);

create policy "Users can insert own profile"
  on public.profiles for insert
  with check ((select auth.uid()) = id);

create policy "Users can update own profile"
  on public.profiles for update
  using ((select auth.uid()) = id);

-- 2. SHIFTS
create table if not exists public.shifts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  client_id text, -- Local device ID for idempotency & offline reconciliation
  shift_date date not null,
  sector text default 'construction' not null,
  employer text,
  location text,
  start_time text,
  end_time text,
  agreed_pay numeric,
  amount_paid numeric,
  is_sunday_or_holiday boolean default false,
  is_encrypted boolean default false,
  ciphertext_payload jsonb,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists idx_shifts_user_id on public.shifts(user_id);
create index if not exists idx_shifts_shift_date on public.shifts(shift_date);

alter table public.shifts enable row level security;

create policy "Users can view own shifts"
  on public.shifts for select
  using ((select auth.uid()) = user_id);

create policy "Users can insert own shifts"
  on public.shifts for insert
  with check ((select auth.uid()) = user_id);

create policy "Users can update own shifts"
  on public.shifts for update
  using ((select auth.uid()) = user_id);

create policy "Users can delete own shifts"
  on public.shifts for delete
  using ((select auth.uid()) = user_id);

-- 3. INCIDENTS (Injuries, Wage Withholding, Maternity Discrimination)
create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  client_id text,
  category text not null check (category in ('injury', 'wages', 'maternity', 'termination', 'safety')),
  incident_date date not null,
  description text,
  employer text,
  location text,
  witnesses text,
  is_encrypted boolean default false,
  ciphertext_payload jsonb,
  created_at timestamptz default now() not null
);

create index if not exists idx_incidents_user_id on public.incidents(user_id);
create index if not exists idx_incidents_category on public.incidents(category);

alter table public.incidents enable row level security;

create policy "Users can view own incidents"
  on public.incidents for select
  using ((select auth.uid()) = user_id);

create policy "Users can insert own incidents"
  on public.incidents for insert
  with check ((select auth.uid()) = user_id);

create policy "Users can update own incidents"
  on public.incidents for update
  using ((select auth.uid()) = user_id);

create policy "Users can delete own incidents"
  on public.incidents for delete
  using ((select auth.uid()) = user_id);

-- 4. EVIDENCE FILES (M-Pesa Screenshots, Receipts, Medical Slips)
create table if not exists public.evidence_files (
  id text primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  parent_type text not null check (parent_type in ('shift', 'incident')),
  parent_id text,
  file_name text not null,
  file_size bigint not null,
  mime_type text not null,
  sha256_hash text not null,
  payment_type text,
  storage_path text,
  notes text,
  created_at timestamptz default now() not null
);

create index if not exists idx_evidence_files_user_id on public.evidence_files(user_id);
create index if not exists idx_evidence_files_sha256 on public.evidence_files(sha256_hash);

alter table public.evidence_files enable row level security;

create policy "Users can view own evidence"
  on public.evidence_files for select
  using ((select auth.uid()) = user_id);

create policy "Users can insert own evidence"
  on public.evidence_files for insert
  with check ((select auth.uid()) = user_id);

create policy "Users can update own evidence"
  on public.evidence_files for update
  using ((select auth.uid()) = user_id);

create policy "Users can delete own evidence"
  on public.evidence_files for delete
  using ((select auth.uid()) = user_id);

-- 5. AUTOMATIC PROFILE CREATION TRIGGER
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email, 'Worker'));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
